version: "3"

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    ports:
      - "80:80"
  db:
    image: "postgres"
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
