version: "3"

services:
  backend:
    image: ivanetscence/ci-newbackend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "3000:3000"
  frontend:
    image: ivanetscence/ci-newfrontend
    depends_on:
      - backend
    ports:
      - "80:80"
  db:
    image: "postgres"
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
